options:
  logging: CLOUD_LOGGING_ONLY

steps:
# STEP 0: Check the commit message.
- name: 'gcr.io/cloud-builders/git' # <-- THIS IS THE FIX. Use the official git image.
  id: 'Check-commit-message'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    commit_message=$(git log -1 --pretty=%B "${COMMIT_SHA}")
    if [[ ! "$commit_message" =~ "gcloud build" ]]; then
      echo "Keyword 'gcloud build' is missing. Failing build."
      exit 1
    else
      echo "Keyword found. Proceeding with build."
    fi

# ---- STEG 1: Build the Docker images in parallel ----
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-scraping'
  args:
    - 'build'
    - '-t'
    - 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/scraping:${COMMIT_SHA}'
    - './scraping'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-geocoding'
  args:
    - 'build'
    - '-t'
    - 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/geocoding:${COMMIT_SHA}'
    - './geocoding'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-modeling'
  args:
    - 'build'
    - '-t'
    - 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/modeling:${COMMIT_SHA}'
    - './modeling'

# ---- STEP 2: Push to Artifact Registry ----
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-scraping'
  waitFor: ['build-scraping']
  args: ['push', 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/scraping:${COMMIT_SHA}']

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-geocoding'
  waitFor: ['build-geocoding']
  args: ['push', 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/geocoding:${COMMIT_SHA}']

- name: 'gcr.io/cloud-builders/docker'
  id: 'push-modeling'
  waitFor: ['build-modeling']
  args: ['push', 'europe-west1-docker.pkg.dev/sibr-market/sibr-market-repo/modeling:${COMMIT_SHA}']

# ---- STEG 3: Kompiler og opprett/oppdater pipeline-schedule ----
- name: 'python:3.11'
  id: 'deploy-pipeline'
  waitFor: ['push-scraping', 'push-modeling',"push-geocoding"]
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    pip install -r pipelines/requirements.txt
    python pipelines/pipeline.py --commit-sha ${COMMIT_SHA}